require "fauxpaas/components/backend_runner"
require "fauxpaas/components/git_runner"
require "fauxpaas/components/instance_repo"
require "fauxpaas/components/paths"
require "fauxpaas/components/system_runner"
require "fauxpaas/components/token"
